#!/usr/bin/env bash
case "$OSTYPE" in
  solaris*) OS="SOLARIS" ;;
  darwin*)  OS="OSX" ;;
  linux*)   OS="LINUX" ;;
  bsd*)     OS="BSD" ;;
esac

if [ "$1" == "" ]; then
  echo 'USAGE: ./remote <build-server>'
  exit 1
fi

build_server=$1

function send() {
    rsync -r . $build_server --update --delete --progress \
        --exclude='out' --exclude='node_modules' --exclude='.git' \
        --exclude='.sass-cache' --exclude='.*.sw*' --exclude='.next';
}

send;

if [ "$OS" == 'LINUX' ]; then
    while inotifywait --exclude '\..*sw.' -r -q -e modify ./; do
        send;
    done
elif [ "$OS" == 'OSX' ]; then
    while fswatch --one-event src/ tasks/; do
        send;
    done
fi
