#!/usr/bin/env node
let registry;
const fs = require('fs');
const cp = require('child_process');
const utils = require('./utils');

if (process.argv[2] === 'production') {
    registry = JSON.parse(fs.readFileSync('registry.json'));
} else {
    registry = JSON.parse(fs.readFileSync('dev_registry.json'));
}


for (let {repo, hash} of registry) {
    const folder = utils.repoToFolder(repo);
    fs.exists(folder, (function(folder, repo, hash, exists) {
        let cmd;
        if (exists) {
            cmd = `cd ${folder} && git checkout ${hash} \
|| git fetch --unshallow && git checkout ${hash} \
|| git pull origin master && git checkout ${hash}`;
            console.log(cmd);
            return cp.exec(cmd, function(err, out){
                if (err != null) {
                    console.error(err);
                    return process.exit(err.code);
                }
            });
        } else {
            cmd = `git clone --depth=1 ${repo} ${folder} \
&& cd ${folder} && git checkout ${hash} \
|| git fetch --unshallow && git checkout ${hash}`;
            console.log(cmd);
            return cp.exec(cmd, function(err, out){
                if (err != null) {
                    console.error(err);
                    return process.exit(err.code);
                }
    });
        }}).bind(undefined, folder, repo, hash)
    );
}
