#!/usr/bin/env python

import sys
import subprocess
import os
import os.path

kicad_file = sys.argv[1]
ibom_file = sys.argv[2]

IBOM = "~/.kicad_plugins/InteractiveHtmlBom/generate_interactive_bom.py"
IBOM_SCRIPT = os.path.expanduser(IBOM)

destdir = os.path.abspath(os.path.dirname(ibom_file))

os.chdir(os.path.dirname(kicad_file))

cmd = ["python", IBOM_SCRIPT,
       "--dest-dir", destdir,
       "--name-format", "interactive_bom",
       "--no-browser",
       os.path.basename(kicad_file)]
subprocess.call(cmd)
