#!/usr/bin/env bash

docker_host=$(ip addr show docker0 | awk '/inet / {print $2}' | cut -f1 -d'/')
dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "
server {
	listen 80 default_server;
	listen [::]:80 default_server;

	server_name _;

	location / {
		proxy_pass http://${docker_host}:1234;
	}

	location /gitlab {

		client_max_body_size 0;

		gzip off;

		## https://github.com/gitlabhq/gitlabhq/issues/694
		## Some requests take more than 30 seconds.
		proxy_read_timeout      300;
		proxy_connect_timeout   300;
		proxy_redirect          off;

		proxy_http_version 1.1;

		proxy_set_header    Host                \$http_host;
		proxy_set_header    X-Real-IP           \$remote_addr;
		proxy_set_header    X-Forwarded-For     \$proxy_add_x_forwarded_for;
		proxy_set_header    X-Forwarded-Proto   \$scheme;

		proxy_pass http://${docker_host}:8079/gitlab;

	}

	location /login/api {
		proxy_pass http://${docker_host}:4004/;
	}

}" > "${dir}/default.conf"
