#!/usr/bin/env bash

docker_host=$(ip addr show docker0 | awk '/inet / {print $2}' | cut -f1 -d'/')
dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source "${dir}/../.env"

echo "
server {
	listen 80 default_server;
	listen [::]:80 default_server;

	server_name _;

	location ^~ / {
		proxy_pass http://${docker_host}:1234;
	}

	location ^~ '/${KITSPACE_GITLAB_PATH}' {
		client_max_body_size 0;

		gzip off;

		## https://github.com/gitlabhq/gitlabhq/issues/694
		## Some requests take more than 30 seconds.
		proxy_read_timeout      300;
		proxy_connect_timeout   300;
		proxy_redirect          off;

		proxy_http_version 1.1;

		proxy_set_header    Host                \$http_host;
		proxy_set_header    X-Real-IP           \$remote_addr;
		proxy_set_header    X-Forwarded-For     \$proxy_add_x_forwarded_for;
		proxy_set_header    X-Forwarded-Proto   \$scheme;

		proxy_cookie_path /${KITSPACE_GITLAB_PATH} /;

		proxy_pass http://${docker_host}:${KITSPACE_GITLAB_PORT}/${KITSPACE_GITLAB_PATH};

	}

	location ^~ '/${KITSPACE_GITLAB_PATH}/users/auth' {
		client_max_body_size 0;

		gzip off;

		## https://github.com/gitlabhq/gitlabhq/issues/694
		## Some requests take more than 30 seconds.
		proxy_read_timeout      300;
		proxy_connect_timeout   300;
		proxy_redirect          off;

		proxy_http_version 1.1;

		proxy_set_header    Host                \$http_host;
		proxy_set_header    X-Real-IP           \$remote_addr;
		proxy_set_header    X-Forwarded-For     \$proxy_add_x_forwarded_for;
		proxy_set_header    X-Forwarded-Proto   \$scheme;

		proxy_cookie_path /${KITSPACE_GITLAB_PATH} /;

		proxy_pass http://${docker_host}:${KITSPACE_GITLAB_PORT}/${KITSPACE_GITLAB_PATH}/users/auth;

	}

	location ^~ '/${KITSPACE_GITLAB_PATH}/users' {
		# allow the login service to access these externally, but no one else
		allow ${KITSPACE_LOGIN_SERVER_IP};
		deny all;
		error_page 403 /login;

		client_max_body_size 0;

		gzip off;

		## https://github.com/gitlabhq/gitlabhq/issues/694
		## Some requests take more than 30 seconds.
		proxy_read_timeout      300;
		proxy_connect_timeout   300;
		proxy_redirect          off;

		proxy_http_version 1.1;

		proxy_set_header    Host                \$http_host;
		proxy_set_header    X-Real-IP           \$remote_addr;
		proxy_set_header    X-Forwarded-For     \$proxy_add_x_forwarded_for;
		proxy_set_header    X-Forwarded-Proto   \$scheme;

		proxy_cookie_path '/${KITSPACE_GITLAB_PATH}' /;

		proxy_pass http://${docker_host}:${KITSPACE_GITLAB_PORT}/${KITSPACE_GITLAB_PATH}/users;

	}

	location ^~ '/${KITSPACE_GITLAB_PATH}/profile' {
		# allow the login service to access these externally, but no one else
		allow ${KITSPACE_LOGIN_SERVER_IP};
		deny all;
		error_page 403 /login;

		client_max_body_size 0;

		gzip off;

		## https://github.com/gitlabhq/gitlabhq/issues/694
		## Some requests take more than 30 seconds.
		proxy_read_timeout      300;
		proxy_connect_timeout   300;
		proxy_redirect          off;

		proxy_http_version 1.1;

		proxy_set_header    Host                \$http_host;
		proxy_set_header    X-Real-IP           \$remote_addr;
		proxy_set_header    X-Forwarded-For     \$proxy_add_x_forwarded_for;
		proxy_set_header    X-Forwarded-Proto   \$scheme;

		proxy_cookie_path '/${KITSPACE_GITLAB_PATH}' /;

		proxy_pass http://${docker_host}:${KITSPACE_GITLAB_PORT}/${KITSPACE_GITLAB_PATH}/profile;

	}

	location ^~ '/${KITSPACE_GITLAB_PATH}/uploads' {
		# allow the login service to access these externally, but no one else
		allow ${KITSPACE_LOGIN_SERVER_IP};
		deny all;
		error_page 403 /login;

		client_max_body_size 0;

		gzip off;

		## https://github.com/gitlabhq/gitlabhq/issues/694
		## Some requests take more than 30 seconds.
		proxy_read_timeout      300;
		proxy_connect_timeout   300;
		proxy_redirect          off;

		proxy_http_version 1.1;

		proxy_set_header    Host                \$http_host;
		proxy_set_header    X-Real-IP           \$remote_addr;
		proxy_set_header    X-Forwarded-For     \$proxy_add_x_forwarded_for;
		proxy_set_header    X-Forwarded-Proto   \$scheme;

		proxy_cookie_path '/${KITSPACE_GITLAB_PATH}' /;

		proxy_pass http://${docker_host}:${KITSPACE_GITLAB_PORT}/${KITSPACE_GITLAB_PATH}/uploads;

	}


	location ^~ '/${KITSPACE_GITLAB_PATH}/api/v4' {

		client_max_body_size 0;

		gzip off;

		## https://github.com/gitlabhq/gitlabhq/issues/694
		## Some requests take more than 30 seconds.
		proxy_read_timeout      300;
		proxy_connect_timeout   300;
		proxy_redirect          off;

		proxy_http_version 1.1;

		proxy_set_header    Host                \$http_host;
		proxy_set_header    X-Real-IP           \$remote_addr;
		proxy_set_header    X-Forwarded-For     \$proxy_add_x_forwarded_for;
		proxy_set_header    X-Forwarded-Proto   \$scheme;

		proxy_cookie_path /${KITSPACE_GITLAB_PATH} /;

		proxy_pass http://${docker_host}:${KITSPACE_GITLAB_PORT}/${KITSPACE_GITLAB_PATH}/api/v4;

	}

	location ^~ '/!login/api' {
		## https://github.com/gitlabhq/gitlabhq/issues/694
		## Some requests take more than 30 seconds.
		proxy_read_timeout      300;
		proxy_connect_timeout   300;
		proxy_redirect          off;

		proxy_http_version 1.1;

		proxy_set_header    Host                \$http_host;
		proxy_set_header    X-Real-IP           \$remote_addr;
		proxy_set_header    X-Forwarded-For     \$proxy_add_x_forwarded_for;
		proxy_set_header    X-Forwarded-Proto   \$scheme;

		proxy_cookie_path /${KITSPACE_GITLAB_PATH} /;

		proxy_pass http://${docker_host}:4004/;
	}

	location ^~ '/!gitlabql' {
		## https://github.com/gitlabhq/gitlabhq/issues/694
		## Some requests take more than 30 seconds.
		proxy_read_timeout      300;
		proxy_connect_timeout   300;
		proxy_redirect          off;

		proxy_http_version 1.1;

		proxy_set_header    Host                \$http_host;
		proxy_set_header    X-Real-IP           \$remote_addr;
		proxy_set_header    X-Forwarded-For     \$proxy_add_x_forwarded_for;
		proxy_set_header    X-Forwarded-Proto   \$scheme;

		proxy_cookie_path /${KITSPACE_GITLAB_PATH} /;

		proxy_pass http://${docker_host}:3000/;
	}

}" > "${dir}/default.conf"
