#!/bin/bash

#exit with non-zero exit code if any process fails
set -e

#  don't do anything on pull-requests
if [ "${TRAVIS_PULL_REQUEST}" != "false" ]
then
    exit 0
elif  [ "${TRAVIS_BRANCH}" != "master" ]
then
    echo -e "User-agent: *\nDisallow: /\n" > build/robots.txt
    echo -e "${SSH_KEY}" > key-file
    chmod 600 key-file
    #replace all occurunces of / with .
    folder=${TRAVIS_BRANCH//\//.}
    rsync --archive --compress --update --delete --recursive -e 'ssh -i key-file -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no' build/ "ubuntu@preview.kitspace.org:preview/${folder}/"
    rm -f key-file
else
    mv build/.temp .
    npx netlify deploy --prod --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --dir=build/
    mv .temp build/
fi
