#!/usr/bin/env node
const fs = require('fs')
const utils = require('./utils')

const repos = utils.readRepos()
const registry = JSON.parse(fs.readFileSync('./registry.json', 'utf8'))

for (let index = 0; index < repos.length; index++) {
  var repo = repos[index]
  const hasVersion = registry.reduce(
    (prev, {repo: r}) => prev || r === repo,
    false
  )
  if (!hasVersion) {
    utils.getVersion(repo, (index, hash) => {
      registry.push({repo, hash})
    })
  }
}
fs.writeFileSync('./registry.json', JSON.stringify(registry, undefined, 2))
